### ISSUE TITLE
Update Readme.md file

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/news-webapp-api#1]
Update readme.md file for this project.

**Comment by sahilrajput18** [comment]
Hey ! can i update the readme.md file for this project and contribute to the hacktoberfest.

**Comment by codemaniac-sahil** [comment]
Yes @sahilrajput18

**Comment by codemaniac-sahil** [comment]
@sahilrajput18 are you working on this?

**Comment by sahilrajput18** [comment]
yes i am ! will update it in next 30 min

**Comment by codemaniac-sahil** [comment]
Okay @sahilrajput18
