### ISSUE TITLE
[Suggestions]

### ISSUE THREAD

**Issue by codeboyfriend** [codemaniac-sahil/news-webapp-api#12]
Change the link from https://harmonious-figolla-9338f7.netlify.app/ to something that is meaningful

This can be done in netlify site from the site setting section

**Comment by codemaniac-sahil** [comment]
I'll do it later

**Comment by codeboyfriend** [comment]
Ok

**Comment by codemaniac-sahil** [comment]
are you able to solve this issue https://github.com/codemaniac-sahil/currency_converter_react/issues/6

**Comment by codeboyfriend** [comment]
It can only be done from your netlify account.. I can only guide you on doing it
