### ISSUE TITLE
Add UI design 

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/news-webapp-api#17]
Add UI design for landing and world page

**Comment by Jaspreet099** [comment]
@codemaniac-sahil review this design

![News com](https://user-images.githubusercontent.com/75212002/193849352-e37ab1f2-f1f0-49e4-982e-512fcc83e00f.jpg)

**Comment by codemaniac-sahil** [comment]
Great work @Jaspreet099
