### ISSUE TITLE
Content of homepage are not in centered

### ISSUE THREAD

**Issue by Laxmankohar** [codemaniac-sahil/news-webapp-api#26]
I would like to add content of homepage in center which makes website looks attractive.
I opened this issue under hacktoberfest 2022
Can you please assign it to me?
![image](https://user-images.githubusercontent.com/73365025/194775953-dbb34e75-2811-4790-b34f-f447aab6a4b3.png)

**Comment by codemaniac-sahil** [comment]
@Laxmankohar you can start working on this issue.

**Comment by Laxmankohar** [comment]
@codemaniac-sahil check it once then i will make a pull request.

![image](https://user-images.githubusercontent.com/73365025/194815287-b51fca97-05fb-4930-82f7-a8c4e4cd418c.png)

**Comment by codemaniac-sahil** [comment]
@Laxmankohar it is too awesome

**Comment by codemaniac-sahil** [comment]
You can send the PR
