### ISSUE TITLE
Add world news page

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/news-webapp-api#3]
Add world news page and add it to homepage.

**Comment by riyaku11** [comment]
I would like to work on this. please assign this to me

**Comment by codemaniac-sahil** [comment]
@riyaku11 you are good to go

**Comment by riyaku11** [comment]
do you want me to fetch world news on the new page?

**Comment by codemaniac-sahil** [comment]
Yes @riyaku11

**Comment by codemaniac-sahil** [comment]
If you are able to fetch the world news on same page then you are good to go with that also.

**Comment by riyaku11** [comment]
okay @codemaniac-sahil

**Comment by riyaku11** [comment]
done @codemaniac-sahil

**Comment by riyaku11** [comment]
please check and merge my pull request

**Comment by codemaniac-sahil** [comment]
I am not able to see world news

**Comment by codemaniac-sahil** [comment]
> do you want me to fetch world news on the new page?

Do this instead

**Comment by codemaniac-sahil** [comment]
show world news on new page

**Comment by riyaku11** [comment]
i have added on the same page

**Comment by riyaku11** [comment]
> If you are able to fetch the world news on same page then you are good to go with that also.

this

**Comment by riyaku11** [comment]
is the world news visible now??

**Comment by codemaniac-sahil** [comment]
> i have added on the same page

but i am not able to see it

do one thing that redirect user on new page for world news

**Comment by riyaku11** [comment]
okay @codemaniac-sahil

**Comment by codemaniac-sahil** [comment]
@riyaku11 I think that will be easy for you

**Comment by riyaku11** [comment]
redirected to a new page from "world" tab in the navbar

**Comment by riyaku11** [comment]
please check @codemaniac-sahil

**Comment by codemaniac-sahil** [comment]
@riyaku11 it is not showing world news

**Comment by codemaniac-sahil** [comment]
remove geolocation api call

**Comment by riyaku11** [comment]
![image](https://user-images.githubusercontent.com/77982135/193545117-7d9db88b-3f37-4733-9b37-9bb79e3dcc05.png)

**Comment by codemaniac-sahil** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/58036566/193545580-5baa2e9b-ebfb-447a-992b-fbb118b6e4bd.png)
This is what happening on my side

**Comment by codemaniac-sahil** [comment]
do one thing make separate script for world news page

**Comment by riyaku11** [comment]
okay

**Comment by codemaniac-sahil** [comment]
I think that will work

**Comment by riyaku11** [comment]
now check @codemaniac-sahil

**Comment by codemaniac-sahil** [comment]
![Screenshot (33)](https://user-images.githubusercontent.com/58036566/193547979-b7a08f12-8401-4a98-9a2c-fd766a1b10fb.png)
I think your API is not working

**Comment by codemaniac-sahil** [comment]
Is it working fine from your side

**Comment by riyaku11** [comment]
give me some time, I will fix it

**Comment by riyaku11** [comment]
please check now @codemaniac-sahil

**Comment by codemaniac-sahil** [comment]
You did great @riyaku11
