### ISSUE TITLE
Navbar Is Not Responsive

### ISSUE THREAD

**Issue by Mustafa-Azad025** [codemaniac-sahil/news-webapp-api#31]
Hey ,
Here In Your Website There Is A Bug In Responsiveness 
![image](https://user-images.githubusercontent.com/97380192/195315195-df7b5777-ba2e-4925-afdd-bfdae8c0052e.png)
I want to contribute to this please assign this task to me

**Comment by codemaniac-sahil** [comment]
@Mustafa-Azad025 you can work on this issue.

**Comment by Mustafa-Azad025** [comment]
Please Merge This In Your Code
