### ISSUE TITLE
Add toggle button

### ISSUE THREAD

**Issue by AditiSingh2003** [codemaniac-sahil/news-webapp-api#35]
**Please describe your idea.**
We can add a toggle button in place of "Dark Mode".

**Describe how the idea would be helpful**
It will make the website more appealing. 
![Screenshot (15)](https://user-images.githubusercontent.com/97729662/195488940-accae467-86f7-4f12-8c3f-4c9570e38c71.png)

**Additional context**

**Comment by lusifer65** [comment]
can you assign to me ?

**Comment by lusifer65** [comment]
i will work on that please check https://github.com/lusifer65/news-webapp-api/tree/toggleBtn and approve that

**Comment by codemaniac-sahil** [comment]
@AditiSingh2003, @lusifer65 has already resolved the issue.

**Comment by codemaniac-sahil** [comment]
@AditiSingh2003, add the toggle button inside the navbar

**Comment by AditiSingh2003** [comment]
Sure
