### ISSUE TITLE
Copyright text

### ISSUE THREAD

**Issue by AditiSingh2003** [codemaniac-sahil/news-webapp-api#36]
**Describe the bug**
The copyright text is moving as the page moves up and down.

**Browser**
Chrome

**Screenshots**

**Additional context**
![Screenshot (17)](https://user-images.githubusercontent.com/97729662/195489622-6489c139-213a-4e8f-bfe5-0bfc75d88e0e.png)

**Comment by lusifer65** [comment]
can you assign to me ?

**Comment by codemaniac-sahil** [comment]
@AditiSingh2003 it is already resolved
