### ISSUE TITLE
Dark mode is not properly applied.

### ISSUE THREAD

**Issue by AditiSingh2003** [codemaniac-sahil/news-webapp-api#39]
**Describe the bug**
The area in navbar is not completely black a strip of white color is left. It makes the website look uneven

**Browser**
Chrome

**Screenshots**
![Screenshot (23)](https://user-images.githubusercontent.com/97729662/195541740-592e6eac-d68a-48de-9b0a-74904daf0e34.png)

**Additional context**

**Comment by codemaniac-sahil** [comment]
Would you please add the toggle button in navigation bar section and also change the text accordingly.

**Comment by AditiSingh2003** [comment]
Yes Sure
