### ISSUE TITLE
upgrade the footer icon

### ISSUE THREAD

**Issue by lusifer65** [codemaniac-sahil/news-webapp-api#40]
**Please describe your idea.**
i want to change the footer icon hover effect

**Comment by lusifer65** [comment]
@codemaniac-sahil can you assign to me

**Comment by codemaniac-sahil** [comment]
@lusifer65 you can work on this case

**Comment by lusifer65** [comment]
ok

**Comment by codemaniac-sahil** [comment]
@lusifer65 please make them visible in dark mode
