### ISSUE TITLE
Improve footer and reduce the reduction of words

### ISSUE THREAD

**Issue by AditiSingh2003** [codemaniac-sahil/news-webapp-api#41]
**Describe the bug**
I want to modify footer and in footer section About Us is written twice.
I want to fix that.

**Browser**
Chrome

**Screenshots**
![Screenshot (24)](https://user-images.githubusercontent.com/97729662/195543489-87a33eec-f0f6-46db-9ee5-20fc4c5d1b35.png)

**Additional context**

**Comment by codemaniac-sahil** [comment]
Okay @AditiSingh2003 you can work on this issue

**Comment by codemaniac-sahil** [comment]
I actually messed up with code while resolving the conflicts

**Comment by AditiSingh2003** [comment]
okay okay

**Comment by Ayushhgupta39** [comment]
Please assign this me
