### ISSUE TITLE
The headlines don't load when maximum number of requests to the API has reached

### ISSUE THREAD

**Issue by thisisamish** [codemaniac-sahil/news-webapp-api#48]
### Describe the bug
The headlines do not load when a maximum number of requests to the API has been reached. There is no error message or any kind of feedback given to the user in this case. I want to fix that with a proper error message.

### Browser
I am using the latest version of Chrome on Windows 11.

### Screenshots
Console screenshot:
![image_160](https://user-images.githubusercontent.com/71922206/195623183-ee81006c-3f0b-44ad-ba8e-2a05c368b787.png)
<br>
Web page screenshot:
![image_161](https://user-images.githubusercontent.com/71922206/195623206-00189ffe-998a-4c3f-b92a-965bd8f8a82c.png)

**Comment by thisisamish** [comment]
@codemaniac-sahil please assign this to me.

**Comment by codemaniac-sahil** [comment]
okay @thisisamish

**Comment by thisisamish** [comment]
#68 PR made by me solved this issue. The PR was merged so I am closing this issue.
