### ISSUE TITLE
Dark Mode button and Navbar Not aligned

### ISSUE THREAD

**Issue by Ayushhgupta39** [codemaniac-sahil/news-webapp-api#51]
**Describe the bug**
The Dark mode button is not inside the navbar and the navbar is not properly assigned. After fixing the issue, it will not be weirdly at the corner but will be at the center.

**Browser**
Google Chrome

**Screenshots**
<img width="948" alt="image" src="https://user-images.githubusercontent.com/96309609/195760535-81ecf1fb-fba7-405d-bd80-3d217eedbe15.png">

**Comment by codemaniac-sahil** [comment]
@Ayushhgupta39 you can start working on this issue

**Comment by yogesh-9999** [comment]
assign it to me
