### ISSUE TITLE
The sizes of the cointainer

### ISSUE THREAD

**Issue by AditiSingh2003** [codemaniac-sahil/news-webapp-api#52]
**Describe the bug**
The size of the box is different in each section.

**Browser**
Chrome

**Screenshots**
![Screenshot (31)](https://user-images.githubusercontent.com/97729662/195761151-cbf842cf-75eb-4e92-8681-1a525accd57a.png)

**Additional context**

**Comment by prashant-jadu** [comment]
I can fix it can you assign me this  issue?

**Comment by codemaniac-sahil** [comment]
sure @prashant-jadu you can work on this issue

**Comment by prashant-jadu** [comment]
can you please assign gacktoberfest-accepted label to my code.
