### ISSUE TITLE
Add transition effect on hovering on news card.

### ISSUE THREAD

**Issue by Aarav238** [codemaniac-sahil/news-webapp-api#53]
**Please describe your idea.**
I will add the hover transition effect on news card.

**Describe how the idea would be helpful**
It Will give user a enhanced experience.

I will add this effect in the below attached section.
![news](https://user-images.githubusercontent.com/95538627/195761375-ee7845c7-8e0e-420c-844d-1d68bedc5642.png)

**Comment by Aarav238** [comment]
@codemaniac-sahil  Please assign this issue to me.

**Comment by codemaniac-sahil** [comment]
@Aarav238 You can work on this issue

**Comment by prashant-jadu** [comment]
can you assign this task to me?

**Comment by codemaniac-sahil** [comment]
@prashant-jadu it is already resolved by @Aarav238
