### ISSUE TITLE
Font style of Footer

### ISSUE THREAD

**Issue by Ayushhgupta39** [codemaniac-sahil/news-webapp-api#58]
**Please describe your idea.**
I would like to make the font-style of footer section more appealing and a lot better.

**Describe how the idea would be helpful**
This would make the website look a lot better, and gain more users.

Please assign me this issue and Add hacktoberfest and hacktoberfest-accepted label.

**Comment by codemaniac-sahil** [comment]
@Ayushhgupta39 You can start working on this issue
