### ISSUE TITLE
Add contact form in Contact Us button

### ISSUE THREAD

**Issue by Ayushhgupta39** [codemaniac-sahil/news-webapp-api#59]
**Please describe your idea.**
I would add a contact form in the contact Us button.

**Describe how the idea would be helpful**
Currently, when we press the contact us button, nothing happens, after adding the form it will open a new page with a contact form.

Please assign me this and add Hacktoberfest and Hacktoberfest-accepted label.

**Comment by codemaniac-sahil** [comment]
@Ayushhgupta39 You can start work on this issue.
