### ISSUE TITLE
No icon inside theme button and dark mode is not functionig properly . 

### ISSUE THREAD

**Issue by Aarav238** [codemaniac-sahil/news-webapp-api#64]
**Describe the bug**
No icon inside theme button and dark mode is not functionig properly . 
As in the below attached screenshot You can see that some of the items of navbar are hidden in dark mode.

**Browser**
Chrome

**Screenshots**
![newsapi](https://user-images.githubusercontent.com/95538627/195970477-8823171e-5e61-4315-84c0-d0ff9a3de16c.png)

**Additional context**

**Comment by Aarav238** [comment]
Please assign it to me and add hactoberfest label.
@codemaniac-sahil

**Comment by codemaniac-sahil** [comment]
yes, @Aarav238 you can start working on this issue
