### ISSUE TITLE
UI Improvements in world news page.

### ISSUE THREAD

**Issue by sahadat-sk** [codemaniac-sahil/news-webapp-api#65]
The UI/UX of the world news page can be improved.
Can I on this?

**Comment by codemaniac-sahil** [comment]
@sahadat-sk yes, you can start work on this issue.

**Comment by sahadat-sk** [comment]
@codemaniac-sahil I have made the PR you can check that out!

**Comment by codemaniac-sahil** [comment]
You did great job @sahadat-sk
