### ISSUE TITLE
on hovering over contact button in dark mode , button colour becomes so dull.

### ISSUE THREAD

**Issue by Aarav238** [codemaniac-sahil/news-webapp-api#75]
**Describe the bug**

on hovering over contact button in dark mode , button colour becomes so dull.
**Browser**
chrome

**Screenshots**
![dkd](https://user-images.githubusercontent.com/95538627/196249579-61546885-8788-4e3a-abfd-3035a698cb6f.png)

**Additional context**

**Comment by codemaniac-sahil** [comment]
@Aarav238 you can start working on this issue
