### ISSUE TITLE
Change the color of the footer

### ISSUE THREAD

**Issue by AditiSingh2003** [codemaniac-sahil/news-webapp-api#83]
**Describe the bug**
the footer section doesn't matches with the overall layout of the website.

**Browser**
Chrome

**Screenshots**
Will make it look like this.
![Screenshot (51)](https://user-images.githubusercontent.com/97729662/197389440-9ccb80ce-91c6-45af-8a8a-5d4647ce84fc.png)

**Comment by heysagnik** [comment]
Can you please share the color codes ? @AditiSingh2003

**Comment by lusifer65** [comment]
can you assing to me

**Comment by codemaniac-sahil** [comment]
yes @lusifer65 you can start work on this issue

**Comment by lusifer65** [comment]
i think this working fine 
![image](https://user-images.githubusercontent.com/42277681/206210575-8b6a868e-3b82-4743-aa84-b82fecb44f41.png)

**Comment by codemaniac-sahil** [comment]
yes @lusifer65
